# AC920 + ACFL3432 FMC_LPC pinout from the vendor CM3432 dual-channel TCP demo.

set_property PACKAGE_PIN D7 [get_ports adc1_clk_p_0]
set_property PACKAGE_PIN F2 [get_ports adc_clk_p_0]
set_property PACKAGE_PIN C9 [get_ports adc1_spi_ce_0]
set_property PACKAGE_PIN B3 [get_ports adc1_spi_io_0]
set_property PACKAGE_PIN B5 [get_ports adc1_spi_sclk_0]
set_property PACKAGE_PIN AH14 [get_ports reset_n_0]

set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc1_clk_p_0]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports adc_clk_p_0]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_spi_ce_0]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_spi_io_0]
set_property IOSTANDARD LVCMOS18 [get_ports adc1_spi_sclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n_0]

set_property PACKAGE_PIN G8 [get_ports {adc1_data_p_0[0]}]
set_property PACKAGE_PIN G5 [get_ports {adc1_data_p_0[1]}]
set_property PACKAGE_PIN G6 [get_ports {adc1_data_p_0[2]}]
set_property PACKAGE_PIN B4 [get_ports {adc1_data_p_0[3]}]
set_property PACKAGE_PIN D4 [get_ports {adc1_data_p_0[4]}]
set_property PACKAGE_PIN C3 [get_ports {adc1_data_p_0[5]}]
set_property PACKAGE_PIN E5 [get_ports {adc1_data_p_0[6]}]
set_property PACKAGE_PIN G1 [get_ports {adc1_data_p_0[7]}]
set_property PACKAGE_PIN G3 [get_ports {adc1_data_p_0[8]}]
set_property PACKAGE_PIN J5 [get_ports {adc1_data_p_0[9]}]
set_property PACKAGE_PIN H9 [get_ports {adc1_data_p_0[10]}]
set_property PACKAGE_PIN J6 [get_ports {adc1_data_p_0[11]}]
set_property PACKAGE_PIN L7 [get_ports {adc1_data_p_0[12]}]
set_property PACKAGE_PIN K8 [get_ports {adc1_data_p_0[13]}]

set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[4]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[5]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[6]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[7]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[8]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[9]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[10]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[11]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[12]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {adc1_data_p_0[13]}]

# Bring-up only: allow bitstream generation while PS-side AXI/AXIS ports are
# still exposed by the standalone RTL top instead of connected in a block design.
set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
