"""Shared network protocol helpers for the SDR project."""

from .control import (
    JsonLineError,
    build_error,
    build_request,
    build_response,
    decode_json_line,
    encode_json_line,
)
from .packets import (
    IQ_HEADER_SIZE,
    PSD_HEADER_SIZE,
    SDR_FRAME_IQ,
    SDR_FRAME_PSD,
    SDR_IQ_FLAG_ADC_OR,
    SDR_IQ_FLAG_CONFIG_CHANGED,
    SDR_IQ_FLAG_DISCONTINUITY,
    SDR_IQ_FLAG_FIFO_OVERFLOW,
    SDR_IQ_MAGIC,
    SDR_PROTOCOL_VERSION,
    SDR_PSD_FLAG_CONFIG_CHANGED,
    SDR_PSD_FLAG_DISCONTINUITY,
    SDR_PSD_FLAG_OVERFLOW,
    SDR_PSD_MAGIC,
    SDR_SAMPLE_SC16_LE,
    SdrIqHeader,
    SdrPsdHeader,
)

__all__ = [
    "IQ_HEADER_SIZE",
    "PSD_HEADER_SIZE",
    "SDR_FRAME_IQ",
    "SDR_FRAME_PSD",
    "SDR_IQ_FLAG_ADC_OR",
    "SDR_IQ_FLAG_CONFIG_CHANGED",
    "SDR_IQ_FLAG_DISCONTINUITY",
    "SDR_IQ_FLAG_FIFO_OVERFLOW",
    "SDR_IQ_MAGIC",
    "SDR_PROTOCOL_VERSION",
    "SDR_PSD_FLAG_CONFIG_CHANGED",
    "SDR_PSD_FLAG_DISCONTINUITY",
    "SDR_PSD_FLAG_OVERFLOW",
    "SDR_PSD_MAGIC",
    "SDR_SAMPLE_SC16_LE",
    "JsonLineError",
    "SdrIqHeader",
    "SdrPsdHeader",
    "build_error",
    "build_request",
    "build_response",
    "decode_json_line",
    "encode_json_line",
]

